apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dependências de DESENVOLVIMENTO/TESTE. Em produção, não use isto: aponte o ConfigMap para serviços gerenciados.
namespace: helpdeskflow

resources:
  - postgres.yaml
  - rabbitmq.yaml
